'use client'

import { useEffect, useState } from 'react'
import { collection, onSnapshot, orderBy, query, doc, updateDoc } from 'firebase/firestore'
import { db } from '@/lib/firebase'
import { useAuth, type UserProfile } from './auth-context'
import { paginate, Pagination } from './pagination'

export function AdminUsers() {
  const { profile } = useAuth(); const [users, setUsers] = useState<UserProfile[]>([]); const [message, setMessage] = useState(''); const [updating, setUpdating] = useState(''); const [page, setPage] = useState(1)
  useEffect(() => { if (profile?.role !== 'admin') return; return onSnapshot(query(collection(db, 'users'), orderBy('email')), (snapshot) => setUsers(snapshot.docs.map((item) => item.data() as UserProfile)), (reason) => setMessage(`Could not load users: ${reason.message}`)) }, [profile?.role])
  async function changeRole(account: UserProfile, role: 'user' | 'organisation') { setUpdating(account.uid); try { await updateDoc(doc(db, 'users', account.uid), { role }); setMessage(`${account.email || account.uid} is now ${role === 'organisation' ? 'an institute' : 'a user'} account.`) } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Unable to update this role.') } finally { setUpdating('') } }
  const visibleUsers = paginate(users, page)
  if (profile?.role !== 'admin') return <section><h1 className="text-3xl font-black">Access denied</h1><p className="mt-3 text-slate-600">Only admins can manage user roles.</p></section>
  return <section className="mx-auto max-w-4xl"><p className="text-sm font-bold tracking-widest text-indigo-600">ADMINISTRATION</p><h1 className="mt-1 text-4xl font-black">Manage access</h1><p className="mt-3 text-slate-600">Promote registered users to institute accounts so they can create mock tests. Admin accounts are deliberately managed only in Firebase.</p>{message && <p className="mt-5 rounded-xl bg-indigo-50 p-4 text-sm text-indigo-800">{message}</p>}<div className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-4 border-b border-slate-200 bg-slate-50 px-5 py-3 text-xs font-bold tracking-wide text-slate-500"><span>ACCOUNT</span><span>ROLE</span></div>{visibleUsers.items.map((account) => <div key={account.uid} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 border-b border-slate-100 px-5 py-4 last:border-0"><div><p className="truncate font-semibold">{account.email || account.uid}</p><p className="mt-1 text-xs text-slate-500">{account.uid}</p></div>{account.role === 'admin' ? <span className="rounded-full bg-violet-100 px-3 py-1.5 text-sm font-bold text-violet-700">Admin</span> : <select value={account.role} disabled={updating === account.uid} onChange={(event) => changeRole(account, event.target.value as 'user' | 'organisation')} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold capitalize outline-none focus:border-indigo-500 disabled:opacity-50"><option value="user">User</option><option value="organisation">Institute</option></select>}</div>)}{users.length === 0 && <p className="p-6 text-slate-500">No registered users found.</p>}<Pagination page={visibleUsers.page} totalItems={users.length} onPageChange={setPage} itemLabel="users" /></div></section>
}
