'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { collection, doc, getDoc, getDocs, query, serverTimestamp, updateDoc, where } from 'firebase/firestore'
import { db } from '@/lib/firebase'
import { useAuth } from './auth-context'
import { MathText, MathTextEditor } from './math-components'
import { paginate, Pagination } from './pagination'
import type { QuestionBankItem, QuestionContent } from './test-types'

const valid = (question: QuestionContent) => question.prompt.trim() && question.options.length === 4 && question.options.every((option) => option.trim())

export function ManageQuestions() {
  const { user, profile } = useAuth(); const [questions, setQuestions] = useState<QuestionBankItem[]>([]); const [message, setMessage] = useState(''); const [page, setPage] = useState(1); const allowed = profile?.role === 'admin' || profile?.role === 'organisation'
  useEffect(() => { if (!user || !allowed) return; const loads = profile?.role === 'admin' ? [getDocs(collection(db, 'questions'))] : [getDocs(query(collection(db, 'questions'), where('createdBy', '==', user.uid)))]; Promise.all(loads).then((results) => setQuestions(results.flatMap((result) => result.docs.map((item) => ({ id: item.id, ...item.data() }) as QuestionBankItem)).sort((a, b) => a.prompt.localeCompare(b.prompt)))).catch((reason) => setMessage(reason.message)) }, [allowed, profile?.role, user])
  async function archive(item: QuestionBankItem) { if (!confirm(`Archive “${item.prompt}”? Existing tests will keep it.`)) return; try { await updateDoc(doc(db, 'questions', item.id), { archivedAt: item.archivedAt ? null : serverTimestamp(), updatedAt: serverTimestamp() }); setQuestions((current) => current.map((question) => question.id === item.id ? { ...question, archivedAt: item.archivedAt ? null : new Date() } : question)) } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Unable to update question.') } }
  const visibleQuestions = paginate(questions, page)
  if (!allowed) return <section><h1 className="text-3xl font-black">Access denied</h1></section>
  return <section className="mx-auto max-w-4xl"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold tracking-widest text-indigo-600">QUESTION BANK</p><h1 className="mt-1 text-4xl font-black">Manage questions</h1><p className="mt-2 text-slate-600">Archived questions cannot be selected for new tests but remain available to existing tests.</p></div><Link href="/tests/create" className="rounded-xl bg-indigo-600 px-4 py-3 font-bold text-white">Create test</Link></div>{message && <p className="mt-5 text-rose-700">{message}</p>}<div className="mt-7 space-y-3">{visibleQuestions.items.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-semibold"><MathText>{item.prompt}</MathText></p><p className="mt-1 text-xs text-slate-500">{item.visibility} · revision {item.revision} · {item.archivedAt ? 'archived' : 'active'}</p></div><div className="flex gap-2"><Link href={`/manage/questions/${item.id}/edit`} className="rounded-lg border border-indigo-200 px-3 py-2 text-sm font-bold text-indigo-700">Edit</Link><button onClick={() => archive(item)} className="rounded-lg border border-rose-200 px-3 py-2 text-sm font-bold text-rose-700">{item.archivedAt ? 'Restore' : 'Archive'}</button></div></div></article>)}{questions.length === 0 && <p className="rounded-xl border border-dashed border-slate-300 p-8 text-slate-500">Questions are added to the bank when you publish a test.</p>}<Pagination page={visibleQuestions.page} totalItems={questions.length} onPageChange={setPage} itemLabel="questions" className="rounded-xl border border-slate-200 bg-white" /></div></section>
}

export function EditQuestion({ id }: { id: string }) {
  const { user, profile } = useAuth(); const router = useRouter(); const [question, setQuestion] = useState<QuestionBankItem | null>(null); const [content, setContent] = useState<QuestionContent>({ prompt: '', options: ['', '', '', ''], correctAnswer: 0 }); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false); const allowed = profile?.role === 'admin' || profile?.role === 'organisation'
  useEffect(() => { getDoc(doc(db, 'questions', id)).then((result) => { if (!result.exists()) return; const item = { id: result.id, ...result.data() } as QuestionBankItem; setQuestion(item); setContent(item) }).catch((reason) => setMessage(reason.message)) }, [id])
  const canEdit = !!question && (profile?.role === 'admin' || question.createdBy === user?.uid)
  function option(index: number, value: string) { const options = [...content.options]; options[index] = value; setContent({ ...content, options }) }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!question || !canEdit || !valid(content)) { setMessage('Complete all four options before saving.'); return } setSaving(true); try { await updateDoc(doc(db, 'questions', id), { prompt: content.prompt.trim(), options: content.options.map((item) => item.trim()), correctAnswer: content.correctAnswer, revision: question.revision + 1, updatedAt: serverTimestamp() }); router.push('/manage/questions') } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Unable to save question.') } finally { setSaving(false) } }
  if (!allowed || (!question && !message)) return <p className="text-slate-500">Loading question…</p>; if (!canEdit) return <section><h1 className="text-3xl font-black">Access denied</h1></section>
  return <section className="mx-auto max-w-3xl"><Link href="/manage/questions" className="text-sm font-bold text-indigo-600">← Question bank</Link><h1 className="mt-5 text-4xl font-black">Edit bank question</h1><form onSubmit={save} className="mt-7 rounded-2xl bg-white p-6 shadow-sm"><MathTextEditor multiline required value={content.prompt} onChange={(prompt) => setContent({ ...content, prompt })} placeholder="Write your question. Use Insert equation for mathematical notation." inputClassName="min-h-28 w-full rounded-lg border border-slate-200 p-3" />{content.options.map((item, index) => <div key={index} className="mt-3 rounded-lg border border-slate-200 p-3"><div className="flex items-start gap-3"><input type="radio" checked={content.correctAnswer === index} onChange={() => setContent({ ...content, correctAnswer: index })} className="mt-2" /><MathTextEditor required value={item} onChange={(value) => option(index, value)} inputClassName="min-w-0 flex-1 rounded-md border border-slate-200 px-2 py-1 outline-none" /></div></div>)}{message && <p className="mt-4 text-sm text-rose-700">{message}</p>}<button disabled={saving} className="mt-6 rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white">{saving ? 'Saving…' : 'Save question'}</button></form></section>
}
